# Dataset selection
Before selecting a model to identify the car and clothing brands present in the dataset, it's important to
understand the available data in more detail. The choice of model to be used in identifying these logos is naturally dependent on the size and quality of the input dataset. In this notebook I look specifically at the brand-by-brand breakdown for the car and clothing brands in the BelgaLogos set. 

#### Data pre-processing
I have extracted all the unique brand labels, from the dataset (26 in total) and tagged them by hand as a 'car', 'clothing' or 'NA' (not applicable) brand. The brand-name -> brand-category dictionary is located in `load_data.py` and used in the function `read_metadata`.

#### Data statistics / image counts
Let's take a look at our available statistical power, after some sensible quality cuts on the data.

In [1]:
# Import full dataset and filter by acceptable bounding-box sizes
import lib.load_data as ld
metadata = ld.read_metadata()
metadata = ld.filter_by_boundingbox(metadata, 10, 800)

In [2]:
# Select only clothing or car brands
car_metadata      = metadata[metadata.category == 'car']
clothing_metadata = metadata[metadata.category == 'clothing']

In [3]:
import lib.util as ut
car_summary      = ut.metadata_count_summary(car_metadata)
clothing_summary = ut.metadata_count_summary(clothing_metadata)
ut.multi_table([car_summary, clothing_summary], ["Car logo image count", "Clothing logo image count"])

Despite the reasonably large size of the total dataset, the number of high-quality annotated images for each logo is rather limited. If we restrict ourselves to the 'OK' images (those images judged by the human assesors to be identifiable without context or prior information) then the largest brand-logo dataset is only 231 images (Nike). The model and methodology selected to solve the problem must therefore be able to handle a small dataset. 

#### Logo proportions

If we take a look at the bounding-box stats for the car, and clothing subsets

In [4]:
car_bbs      = ut.compute_bb_properties(car_metadata).describe()
clothing_bbs = ut.compute_bb_properties(clothing_metadata).describe()
ut.multi_table([car_bbs, clothing_bbs], ["Car dataset", "Clothing dataset"])

We can see that in general the logos form a very small part of the parent images. This is particuarly true of the clothing dataset, where the average image dimensions are 33px by 26px. The clothing dataset makes up for this by having many more images in the sample, ~4500 vs ~1200 for the car dataset.